services:
  
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8000:5000"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "5800:5800"
      - "5900:5900"
    