services:
  
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8000:5000"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8080:8080"
      - "5900:5900"
      - "6080:6080"

