services:
  
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8000:5000"

  client1:
    build:
      context: .
      dockerfile: clientTest.Dockerfile
    ports:
      - "8001:5001"
    environment:
      - GAME=1
      - NICKNAME=aa
    command: "./gradlew test --tests app.game.GameTest"

  client2:
    build:
      context: .
      dockerfile: clientTest.Dockerfile
    ports:
      - "8002:5001"
    environment:
      - NICKNAME=bb
    command: "./gradlew test --tests app.game.GameTest"

  client3:
    build:
      context: .
      dockerfile: clientTest.Dockerfile
    ports:
      - "8003:5001"
    depends_on:
      client1:
        condition: service_completed_successfully
    environment:
      - NICKNAME=cc
    command: "./gradlew test --tests app.lobby.ClientTest --tests app.lobbySelector.ClientServerInteractionsTest"

#  client4:
#    build:
#      context: .
#      dockerfile: clientTest.Dockerfile
#    ports:
#      - "8004:5001"
#    environment:
#      - NICKNAME=bb
#    command: "./gradlew test --tests app.lobby.ClientTest --tests app.lobbySelector.ClientServerInteractionsTest"
